name: Build Manual

on:
  workflow_dispatch:

jobs:
  buildManual:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Embed version
        run: |
          cd $env:GITHUB_WORKSPACE
          cmd /c version.bat

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Compile
        run: msbuild.exe $env:GITHUB_WORKSPACE\PolicyPlus\PolicyPlus.sln /p:platform="Any CPU" /p:configuration="Release" -verbosity:diag
        
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: PolicyPlus-release
          #path:'$env:GITHUB_WORKSPACE\PolicyPlus\bin\release'
          path: bin\release\
