name: Build Manual

#on: [push, workflow_dispatch]
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
jobs:
  buildManual:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'lordcyb3r/PolicyPlus'
        
      - name: Embed version
        run: |
          echo $env:GITHUB_WORKSPACE
          cd $env:GITHUB_WORKSPACE
          cmd /c version.bat

      - name: Set up MSBuild
        #uses: microsoft/setup-msbuild@v1.0.2
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Compile
        run: msbuild.exe $env:GITHUB_WORKSPACE\PolicyPlus\PolicyPlus.sln /p:platform="Any CPU" /p:configuration="Release" #-verbosity:diag
        
      - name: output debug
        run: |
          echo 'Folder Structure:'
          echo $env:GITHUB_WORKSPACE
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: PolicyPlus-release
          #path:'$env:GITHUB_WORKSPACE\PolicyPlus\PolicyPlus\bin\Release\'
          #path: /bin/release/
          path: 'D:\a\PolicyPlus\PolicyPlus\PolicyPlus\bin\Release\'
